### ISSUE TITLE
Column block

### ISSUE THREAD

**Issue by JiangLong2019** [aemsites/suncorp#14]
Column block that supports the following variations.
1. 
<img width="1265" alt="image" src="https://github.com/user-attachments/assets/00d4b3f6-f855-4309-a2f3-2778e4080cd9">

2. 
<img width="1267" alt="image" src="https://github.com/user-attachments/assets/fce81b64-446d-4e55-b01c-b216b26b4dd1">

https://www.terrischeer.com.au/

**Comment by JiangLong2019** [comment]
Hi @anuj-adobe, can you please help to check if the following parts can reuse the column block or if we need to create new variations?

1. 
<img width="1236" alt="image" src="https://github.com/user-attachments/assets/e1c717ba-3b2d-4b72-90af-e458d459b656">

2. 
<img width="1220" alt="image" src="https://github.com/user-attachments/assets/dfbfe5f1-7db0-4211-962d-45bea872135d">

https://www.terrischeer.com.au/landlord-insurance/

**Comment by anuj-adobe** [comment]
I think we will need new variations.
